# Generated by Django 4.0 on 2021-12-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(choices=[('arka_news', 'ARKA NEWS'), ('arka_facts', 'ARKA FACTS'), ('events', 'ARKA Events')], max_length=20)),
                ('title', models.CharField(max_length=230)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_url', models.CharField(blank=True, default=None, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('admission_number', models.CharField(max_length=200)),
                ('Arka_department', models.CharField(choices=[], max_length=100)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='./members')),
            ],
        ),
    ]
