# Generated by Django 4.0 on 2021-12-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_videomodel_alter_postmodel_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='Arka_department',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
