# Generated by Django 4.0 on 2021-12-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_teammember_arka_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='graduated',
            field=models.BooleanField(default=False),
        ),
    ]
