# Generated by Django 4.0 on 2021-12-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_postmodel_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('video_url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='post',
            field=models.CharField(choices=[('arka_news', 'ARKA NEWS'), ('arka_blogs', 'ARKA BLOGS'), ('arka_events', 'ARKA EVENTS')], max_length=20),
        ),
    ]
