# Generated by Django 4.0 on 2021-12-30 04:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_teammember_graduated'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 12, 30, 4, 46, 43, 720742, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='post',
            field=models.CharField(choices=[('arka_news', 'ARKA NEWS'), ('arka_blogs', 'ARKA BLOGS'), ('arka_facts', 'ARKA FACTS'), ('arka_events', 'ARKA EVENTS')], max_length=20),
        ),
    ]
