# Generated by Django 4.0 on 2021-12-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_postmodel_uploaded_at_alter_postmodel_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='admission_year',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='status',
            field=models.CharField(blank=True, choices=[('Coordinator', 'Coordinator'), ('Member', 'Member'), ('Founder', 'Founder')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='post',
            field=models.CharField(choices=[('ARKA NEWS', 'ARKA NEWS'), ('ARKA FACTS', 'ARKA FACTS'), ('ARKA EVENTS', 'ARKA EVENTS')], max_length=20),
        ),
    ]
