# Generated by Django 4.0 on 2021-12-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_teammember_admission_year_teammember_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='admission_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
