# Generated by Django 4.0 on 2021-12-31 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_teammember_admission_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='graduated',
            new_name='alumnnus',
        ),
    ]
