# Generated by Django 4.0 on 2021-12-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_rename_graduated_teammember_alumnnus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='alumnnus',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='status',
            field=models.CharField(blank=True, choices=[('Coordinator', 'Coordinator'), ('Member', 'Member'), ('Founder', 'Founder'), ('Alumnus', 'Alumnus')], max_length=100, null=True),
        ),
    ]
