# Generated by Django 4.0 on 2021-12-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_remove_teammember_alumnnus_alter_teammember_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='fb_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='insta_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linked_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
