# Generated by Django 4.0 on 2022-01-02 22:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_teammember_profile_pic_alter_teammember_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
