# Generated by Django 4.0 on 2022-01-03 16:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_announcements_postmodel_fb_url_postmodel_insta_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
