# Generated by Django 4.0 on 2022-01-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_alter_announcements_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='profile_pic',
            field=models.ImageField(default=0, upload_to='./notices'),
            preserve_default=False,
        ),
    ]
