# Generated by Django 4.0 on 2022-01-03 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_announcements_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcements',
            old_name='profile_pic',
            new_name='image',
        ),
    ]
