# Generated by Django 4.0 on 2022-01-05 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_rename_profile_pic_announcements_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='upldated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 1, 5, 0, 56, 23, 68969)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcements',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 1, 5, 0, 56, 40, 10030)),
            preserve_default=False,
        ),
    ]
